Use write_all instead of write
This actually fixes a quite important bug, where not the whole frame
would be written in some cases:

    error: written amount is not handled
       --> src/server/mod.rs:159:21
        |
    159 |                     stream.write(&encoded).unwrap();
        |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |
        = help: use `Write::write_all` instead, or handle partial writes
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_io_amount
        = note: `#[deny(clippy::unused_io_amount)]` on by default