Fix panic when passing the reconnect flag
docopt wasn't able to decode directly to the ClientId type. So we decode
into an u32 and convert it before passing it to the Message constructor.

```
     Running `target/debug/cli_client -r 0`
thread '<main>' panicked at 'Unrecognized struct field: '_field0'', /home/roughl/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/docopt-0.6.80/src/dopt.rs:481
```